Completed register user and login UI tests
CloudClub-uoft/cloud-club-website pull request #71
Opened 2022-05-22 17:00 UTC by qingyuan-wu

2022-05-22 20:50 UTC, harsimrat99 requested changes
Hi @qingyuan-wu,

Thank you for creating this pull request and for adding the tests for login and register pages. It would helpful if you could please review the feedback shared in this review.

Thank you,
Harsimrat

2022-05-22 20:50 UTC, harsimrat99 commented on test/frontend/forum/test_forum.py
> +    driver = login()
driver = login()

The username and password must be passed to this function.

2022-05-22 20:50 UTC, harsimrat99 commented on test/frontend/login/test_login.py
> +    driver = login(email, password)
Error: login not found.

Must be resolved by importing the **login** function from the login.py module. 

Please add "from login import *" before running test_login.

2022-05-28 14:00 UTC, qingyuan-wu commented
All changes requested completed including implementing the unittest module. Conflicts with staging branch also resolved. Can merge

2022-05-29 00:51 UTC, harsimrat99 approved these changes

2022-05-29 00:52 UTC, harsimrat99 approved these changes

2022-05-29 00:52 UTC, merged

2022-05-29 00:56 UTC, harsimrat99 commented
Hi @qingyuan-wu ,

Thank you for making the requested changes and for your help with the testcases.

For completeness' sake I have also added the unittest classes to the login and register testcases. Thank you for your help with Selenium and frontend testcase development.

Best,
Harsimrat

2022-05-29 13:12 UTC, qingyuan-wu commented
Thanks for implementing the unittest classes for login and register tests!

Qingyuan